import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Health Data Consent — IbisLabs",
  description:
    "Learn how Ibis Labs collects, uses, stores, and processes your health and wellness information.",
};

const lastUpdated = "March 22, 2026";

type ContentItem = {
  heading?: string;
  text?: string;
  bold?: boolean;
  list?: string[];
  links?: { icon: string; label: string; href: string }[];
};

type Section = {
  id: string;
  title: string;
  content: ContentItem[];
};

const sections: Section[] = [
  {
    id: "purpose-of-this-consent",
    title: "Purpose of this consent",
    content: [
      {
        text: "Ibis Labs offers tools intended to help users track symptoms, understand patterns, and support digestive wellness. To provide these features, we may collect and process information that relates to your health, symptoms, habits, and lifestyle.",
      },
      {
        text: "This Health Data Consent is intended to give you a clear explanation of:",
        list: [
          "what kinds of health and wellness information we may process;",
          "why we process that information;",
          "how Apple Health data may be used if you choose to connect it;",
          "your choices regarding permissions, access, and deletion; and",
          "the limits of the Services.",
        ],
      },
    ],
  },
  {
    id: "wellness-and-medical-notice",
    title: "Important wellness and medical notice",
    content: [
      {
        text: "Ibis Labs is a wellness and informational service. It is not a doctor, medical provider, emergency service, or diagnostic tool.",
      },
      {
        text: "Your use of the Services does not create a physician-patient, therapist-patient, dietitian-patient, or other healthcare-provider relationship with Ibis Labs.",
      },
      {
        text: "Any summaries, trends, correlations, scores, reminders, or insights generated by the Services are for general wellness and informational purposes only. They may be incomplete, inaccurate, delayed, or not appropriate for your specific circumstances.",
      },
      {
        text: "You should always seek advice from a licensed healthcare professional regarding medical concerns, worsening symptoms, possible medication or supplement interactions, pregnancy, significant dietary changes, or treatment decisions.",
      },
      {
        text: "Do not use Ibis Labs for emergencies. If you think you may be having a medical emergency, call 911 or your local emergency number immediately and seek emergency care.",
        bold: true,
      },
    ],
  },
  {
    id: "categories-of-health-information",
    title: "Categories of health and wellness information we may process",
    content: [
      {
        text: "Depending on how you use the Services, we may collect, receive, generate, or process health and wellness information such as:",
        list: [
          "digestive symptoms and symptom severity;",
          "bowel movement and stool logs;",
          "urgency, pain, bloating, discomfort, or related digestive entries;",
          "food, meal, ingredient, hydration, and nutrition entries;",
          "stress, mood, sleep, and lifestyle data;",
          "menstrual or cycle-related information, if you choose to provide it;",
          "personal notes or journal entries you add to the app;",
          "progress data, patterns, or trends generated from your entries;",
          "information from Apple Health or other integrations that you explicitly authorize.",
        ],
      },
      {
        text: "You control what information you manually enter into the Services. If you choose not to provide certain information, some features may not function fully or may not be available.",
      },
    ],
  },
  {
    id: "apple-health-integration",
    title: "Apple Health and device integration data",
    content: [
      {
        text: "If you choose to connect Apple Health or another supported data source, Ibis Labs may access only the categories of data you specifically authorize through your device and permission settings.",
      },
      {
        text: "Depending on what you allow, this may include data such as:",
        list: [
          "sleep-related information;",
          "activity or movement data;",
          "heart rate or related wellness metrics;",
          "other health or fitness categories you choose to share.",
        ],
      },
      {
        text: "You may revoke access at any time through your device settings or Apple Health settings. If you revoke access, some app features may become limited or unavailable.",
      },
    ],
  },
  {
    id: "how-we-use-health-information",
    title: "How we use health and wellness information",
    content: [
      {
        text: "We may use your health and wellness information to:",
        list: [
          "provide symptom tracking, logging, and wellness features;",
          "generate personal summaries, progress views, and pattern-based insights;",
          "support personalization within the app;",
          "improve feature quality, performance, and reliability;",
          "troubleshoot technical issues and provide customer support;",
          "protect the security and integrity of the Services;",
          "conduct internal analytics and product improvement;",
          "understand overall user needs, symptom trends, and feature demand in aggregated or de-identified form;",
          "comply with applicable law and enforce our policies and agreements.",
        ],
      },
      {
        text: "Where possible, we may also use de-identified or aggregated information derived from user data for internal reporting, product development, forecasting, benchmarking, and service improvement.",
      },
    ],
  },
  {
    id: "what-we-do-not-use-health-data-for",
    title: "What we do not use health data for",
    content: [
      {
        text: "As a product and privacy policy, Ibis Labs does not use HealthKit data for advertising, marketing, or use-based data mining.",
        bold: true,
      },
      {
        text: "Ibis Labs does not sell HealthKit data.",
        bold: true,
      },
      {
        text: "Ibis Labs also does not knowingly use your health or symptom data for targeted advertising or behavioral advertising profiling.",
      },
      {
        text: "These restrictions are important because Apple's current rules limit how HealthKit and other health-context data may be used, and U.S. regulators also expect consumer health apps to handle breach and privacy obligations carefully.",
      },
    ],
  },
  {
    id: "who-may-process-this-information",
    title: "Who may process this information",
    content: [
      {
        text: "Your health and wellness information may be processed by Ibis Labs and by service providers acting on our behalf, such as vendors that support:",
        list: [
          "cloud hosting and secure data storage;",
          "authentication and account services;",
          "analytics, diagnostics, and crash reporting;",
          "customer support;",
          "email, notification, and infrastructure tools;",
          "security and fraud prevention.",
        ],
      },
      {
        text: "These providers are permitted to access information only as needed to provide services to us and subject to contractual and operational restrictions.",
      },
    ],
  },
  {
    id: "retention-and-deletion",
    title: "Retention and deletion",
    content: [
      {
        text: "We retain health and wellness information for as long as reasonably necessary to:",
        list: [
          "operate and maintain your account;",
          "provide the Services;",
          "improve and secure the Services;",
          "comply with legal obligations;",
          "resolve disputes; and",
          "enforce our agreements.",
        ],
      },
      {
        text: "If you delete your account or request deletion, we will delete or de-identify your personal information unless we are legally required or permitted to retain certain information for security, compliance, fraud prevention, financial recordkeeping, or similar purposes.",
      },
    ],
  },
  {
    id: "your-choices",
    title: "Your choices",
    content: [
      {
        text: "You have choices about your health and wellness information.",
      },
      {
        text: "You may:",
        list: [
          "choose what information to enter manually;",
          "decide whether to connect Apple Health;",
          "revoke Apple Health permissions at any time in your device settings;",
          "stop using the Services at any time;",
          "request deletion of your account and personal information as described in our Privacy Policy.",
        ],
      },
      {
        text: "Please note that revoking permissions or deleting information may reduce functionality or prevent certain features from working.",
      },
    ],
  },
  {
    id: "limits-of-the-services",
    title: "Limits of the services",
    content: [
      {
        text: "You understand and agree that:",
        list: [
          "the Services are not intended to diagnose, treat, cure, or prevent any disease;",
          "insights may reflect correlations and patterns, not proven causation;",
          "wellness recommendations may not be right for every user;",
          "some users may experience no improvement or no meaningful benefit;",
          "information from Apple Health, devices, or manual entries may be inaccurate or incomplete;",
          "any decision you make based on the Services is your responsibility.",
        ],
      },
    ],
  },
  {
    id: "consent-to-processing",
    title: "Consent to processing",
    content: [
      {
        text: "By selecting \"I Agree,\" using health-related features, entering health or wellness information, or authorizing Apple Health access, you expressly consent to Ibis Labs collecting, storing, using, analyzing, and processing your health and wellness information as described in this Health Data Consent, our Privacy Policy, and our Terms of Use.",
      },
      {
        text: "If you do not agree to this Health Data Consent, do not use health-related features of the Services and do not connect Apple Health.",
        bold: true,
      },
    ],
  },
  {
    id: "changes-to-this-consent",
    title: "Changes to this consent",
    content: [
      {
        text: "We may update this Health Data Consent from time to time. If we make material changes, we may provide notice through the app, website, email, or other reasonable means. The updated version will become effective on the date shown above.",
      },
      {
        text: "Your continued use of health-related features after the effective date of an updated version means the updated version applies going forward.",
      },
    ],
  },
];

export default function HealthDataConsentPage() {
  return (
    <div className="pt-16 min-h-screen bg-[#FAF7F2]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24">

        {/* Header */}
        <div className="mb-16">
          <p className="text-xs font-semibold uppercase tracking-widest text-[#4A7C59] mb-5">
            Legal
          </p>
          <h1
            style={{ fontFamily: "var(--font-playfair)" }}
            className="text-5xl sm:text-6xl font-bold text-[#1C1C1A] tracking-tight leading-tight mb-6"
          >
            Health Data Consent
          </h1>
          <p className="text-[#6B6B67] text-lg leading-relaxed max-w-2xl">
            This Health Data Consent explains how Ibis Labs collects, uses, stores, and
            processes health and wellness information when you use the Services.
          </p>
          <p className="text-xs text-[#6B6B67]/60 mt-4">
            Last updated: {lastUpdated}
          </p>
        </div>

        {/* Consent notice badge */}
        <div className="bg-white border border-[#E8E4DC] rounded-2xl p-6 shadow-sm mb-12 flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-[#4A7C59]/10 flex items-center justify-center flex-shrink-0">
            <svg
              className="w-5 h-5 text-[#4A7C59]"
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"
              />
            </svg>
          </div>
          <div>
            <h2 className="font-bold text-[#1C1C1A] tracking-tight mb-1">
              Your consent matters
            </h2>
            <p className="text-[#6B6B67] text-sm leading-relaxed">
              By enabling health-related features, connecting Apple Health, or entering
              health or wellness information into the Services, you acknowledge that you
              have read and understood this Health Data Consent.
            </p>
          </div>
        </div>

        {/* Table of contents */}
        <div className="bg-white border border-[#E8E4DC] rounded-2xl p-6 shadow-sm mb-12">
          <h2 className="text-xs font-bold text-[#6B6B67] tracking-widest uppercase mb-4">
            Contents
          </h2>
          <ol className="space-y-2">
            {sections.map((section, i) => (
              <li key={section.id}>
                <a
                  href={`#${section.id}`}
                  className="text-sm text-[#4A7C59] hover:underline underline-offset-2"
                >
                  {i + 1}. {section.title.charAt(0).toUpperCase() + section.title.slice(1)}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* Consent sections */}
        <div className="space-y-10">
          {sections.map((section, i) => (
            <div
              key={section.id}
              id={section.id}
              className="bg-white border border-[#E8E4DC] rounded-2xl p-8 shadow-sm scroll-mt-24"
            >
              <div className="flex items-center gap-3 mb-6">
                <span className="text-xs font-bold text-[#4A7C59]/50 tracking-widest">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <h2
                  style={{ fontFamily: "var(--font-playfair)" }}
                  className="text-2xl font-bold text-[#1C1C1A] tracking-tight"
                >
                  {section.title.charAt(0).toUpperCase() + section.title.slice(1)}
                </h2>
              </div>
              <div className="space-y-5">
                {section.content.map((item, j) => (
                  <div key={j}>
                    {item.heading && (
                      <h3 className="font-bold text-[#1C1C1A] tracking-tight mb-1.5 text-base">
                        {item.heading}
                      </h3>
                    )}
                    {item.text && (
                      <p
                        className={
                          item.bold
                            ? "text-sm font-semibold text-[#1C1C1A]"
                            : "text-[#6B6B67] text-sm leading-relaxed"
                        }
                      >
                        {item.text}
                      </p>
                    )}
                    {item.list && (
                      <ul className="mt-3 space-y-2">
                        {item.list.map((li, k) => (
                          <li key={k} className="flex items-start gap-2.5 text-[#6B6B67] text-sm leading-relaxed">
                            <span className="w-1.5 h-1.5 rounded-full bg-[#4A7C59] mt-1.5 flex-shrink-0" />
                            {li}
                          </li>
                        ))}
                      </ul>
                    )}
                    {item.links && (
                      <div className="mt-4 space-y-2">
                        {item.links.map((link) => (
                          <a
                            key={link.href}
                            href={link.href}
                            className="flex items-center gap-2 text-sm text-[#4A7C59] hover:underline underline-offset-2"
                          >
                            <span>{link.icon}</span>
                            {link.label}
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-12 text-center">
          <p className="text-sm text-[#6B6B67] leading-relaxed">
            This Health Data Consent may be updated periodically. We will notify you of
            material changes via an in-app notice or other appropriate means before they take effect.
          </p>
        </div>
      </div>
    </div>
  );
}
